apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "manilacsi.openshift.io/v1alpha1",
          "kind": "ManilaCSI",
          "metadata": {
            "name": "example-manilacsi",
            "namespace": "manila-csi"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: csi-driver-manila-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ManilaCSI is the Schema for the manilacsis API
      kind: ManilaCSI
      name: manilacsis.manilacsi.openshift.io
      version: v1alpha1
  description: Placeholder description
  displayName: Csi Driver Manila Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - watch
          - list
          - update
          - patch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - watch
          - list
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - update
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - update
          - watch
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - list
          - update
          - watch
          - create
          - patch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
          - create
        - apiGroups:
          - storage.k8s.io
          resources:
          - csinodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots/status
          verbs:
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - list
          - watch
          - delete
          - get
          - update
        - apiGroups:
          - cloudcredential.openshift.io
          resources:
          - credentialsrequests
          verbs:
          - create
          - list
          - watch
          - delete
          - get
        serviceAccountName: csi-driver-manila-operator
      deployments:
      - name: csi-driver-manila-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: csi-driver-manila-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: csi-driver-manila-operator
            spec:
              containers:
              - command:
                - csi-driver-manila-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: csi-driver-manila-operator
                - name: EXTERNAL_PROVISIONER_IMAGE
                  value: quay.io/openshift/origin-csi-external-provisioner:latest
                - name: EXTERNAL_SNAPSHOTTER_IMAGE
                  value: quay.io/openshift/origin-csi-external-snapshotter:latest
                - name: CSI_DRIVER_MANILA_IMAGE
                  value: quay.io/openshift/origin-csi-driver-manila:latest
                - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
                  value: quay.io/openshift/origin-csi-node-driver-registrar:latest
                - name: CSI_DRIVER_NFS_IMAGE
                  value: quay.io/openshift/origin-csi-driver-nfs:latest
                image: quay.io/openshift/origin-csi-driver-manila-operator:latest
                imagePullPolicy: Always
                name: csi-driver-manila-operator
                resources: {}
              serviceAccountName: csi-driver-manila-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - csi-driver-manila-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - manilacsi.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: csi-driver-manila-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  replaces: csi-driver-manila-operator.v0.0.0
  version: 0.0.1
