apiVersion: v1
kind: Pod
metadata:
  name: existing-nfs-share-pod
spec:
  containers:
    - name: hello-manila
      image: gcr.io/hello-minikube-zero-install/hello-node
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: existing-nfs-share-pvc
        readOnly: false
