apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver-manila-operator
  namespace: openshift-manila-csi-driver-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csi-driver-manila-operator
  template:
    metadata:
      labels:
        name: csi-driver-manila-operator
    spec:
      serviceAccountName: csi-driver-manila-operator
      containers:
        - name: csi-driver-manila-operator
          image: quay.io/openshift/origin-csi-driver-manila-operator:4.5
          command:
          - csi-driver-manila-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csi-driver-manila-operator"
            - name: EXTERNAL_PROVISIONER_IMAGE
              value: "quay.io/openshift/origin-csi-external-provisioner:4.5"
            - name: EXTERNAL_SNAPSHOTTER_IMAGE
              value: "quay.io/openshift/origin-csi-external-snapshotter:4.5"
            - name: CSI_DRIVER_MANILA_IMAGE
              value: "quay.io/openshift/origin-csi-driver-manila:4.5"
            - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
              value: "quay.io/openshift/origin-csi-node-driver-registrar:4.5"
            - name: CSI_DRIVER_NFS_IMAGE
              value: "quay.io/openshift/origin-csi-driver-nfs:4.5"
