kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-driver-manila-operator
  namespace: manila-csi
subjects:
- kind: ServiceAccount
  name: csi-driver-manila-operator
roleRef:
  kind: Role
  name: csi-driver-manila-operator
  namespace: manila-csi
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-driver-manila-operator
subjects:
- kind: ServiceAccount
  name: csi-driver-manila-operator
  namespace: manila-csi
roleRef:
  kind: ClusterRole
  name: csi-driver-manila-operator
  apiGroup: rbac.authorization.k8s.io