apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-manila-csi-driver
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: manila-cloud-credentials
    namespace: openshift-manila-csi-driver
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
